
// [AntigravityChinesePack V2 DOM Observer Injected]
(function() {
    // 避免在某些纯 worker 或不含 DOM 的环境中报错
    if (typeof document === 'undefined' || !document.body) return;
    
    console.log("[AntigravityChinesePack] V2 Dynamic DOM Observer Active");
    const dict = {
  "Agent Auto-Fix Lints": "Agent 自动修复 Lint",
  "Strict Mode": "严格模式",
  "Review Policy": "审查策略",
  "Terminal Command Auto Execution": "终端命令自动执行",
  "Agent Gitignore Access": "Agent Gitignore 访问",
  "Agent Non-Workspace File Access": "Agent 非工作区文件访问",
  "Auto-Continue": "自动继续",
  "Enable Sounds for Agent": "Agent 声音提示",
  "Auto-Expand Changes Overview": "自动展开更改概览",
  "Conversation History": "对话历史",
  "Knowledge": "知识库",
  "Auto-Open Edited Files": "自动打开已编辑文件",
  "Open Agent on Reload": "重新加载时打开 Agent",
  "Enable Terminal Sandbox": "启用终端沙盒",
  "Sandbox Allow Network": "沙盒允许网络",
  "Suggestions in Editor": "编辑器中的建议",
  "Show Selection Actions": "显示选中操作",
  "Tab Speed": "Tab 速度",
  "Tab to Jump": "Tab 跳转",
  "Tab to Import": "Tab 导入",
  "Highlight After Accept": "接受后高亮",
  "Tab Gitignore Access": "Tab Gitignore 访问",
  "Enable Browser Tools": "启用浏览器工具",
  "Browser Javascript Execution Policy": "浏览器 JavaScript 执行策略",
  "Chrome Binary Path": "Chrome 可执行文件路径",
  "Browser User Profile Path": "浏览器用户配置路径",
  "Browser CDP Port": "浏览器 CDP 端口",
  "Browser URL Allowlist": "浏览器 URL 允许列表",
  "Marketplace Item URL": "市场扩展页面 URL",
  "Marketplace Gallery URL": "市场搜索 URL",
  "Allow List Terminal Commands": "终端命令允许列表",
  "Deny List Terminal Commands": "终端命令拒绝列表",
  "Enable Telemetry": "启用遥测",
  "Always Proceed": "始终继续",
  "Agent Decides": "Agent 决定",
  "Request Review": "请求审查",
  "[Dev] GCP Project ID": "[开发] GCP 项目 ID",
  "Settings -": "设置 -",
  "Conversation mode": "对话模式",
  "Agent can plan before executing tasks. Use for deep research, complex tasks, or collaborative work": "Agent 可以在执行任务前进行规划。适用于深度研究、复杂任务或协作工作",
  "Agent will execute tasks directly. Use for simple tasks that can be completed faster": "Agent 将直接执行任务。适用于可以更快完成的简单任务",
  "Provide Feedback": "提供反馈",
  "Accept": "接受",
  "Accept all": "全部接受",
  "Skip": "跳过",
  "Add": "添加",
  "Add Model": "添加模型",
  "Add context": "添加上下文",
  "Add them to allow future interactions": "将它们添加到允许列表以允许未来的交互",
  "Edit": "编辑",
  "Edit Model": "编辑模型",
  "Editor": "编辑器",
  "Editor Settings": "编辑器设置",
  "Editor Window": "编辑器窗口",
  "Loading...": "加载中...",
  "Loading models...": "正在加载模型...",
  "Loading Browser recording...": "正在加载浏览器录制...",
  "Loading knowledge items...": "正在加载知识项...",
  "Loading metrics...": "正在加载指标...",
  "Undo": "撤销",
  "Discard all changes": "放弃所有更改",
  "Discard changes": "放弃更改",
  "Run": "运行",
  "Running": "运行中",
  "Close": "关闭",
  "Ran command": "行行命令",
  "Close Workspace": "关闭工作区",
  "Delete Conversation": "删除对话",
  "Start Conversation": "开始对话",
  "Open Workspace": "打开工作区",
  "Open New Workspace": "打开新工作区",
  "Open New Remote Workspace": "打开新远程工作区",
  "Start a new conversation": "开始新对话",
  "Start conversation": "开始对话",
  "Proceed": "继续",
  "Artifacts": "产物",
  "Model": "模型",
  "Expand All": "全部展开",
  "Collapse All": "全部折叠",
  "Ask anything, @ to mention, / for workflows": "输入任何内容，@ 用于提及，/ 用于调用工作流",
  "Collapse all": "全部折叠",
  "Thought Process": "思考过程",
  "Auto-proceeded by the agent under your review policy.": "已由 Agent 根据您的审查策略自动继续。",
  "Manually proceeded under your review policy.": "已根据您的审查策略手动继续。",
  "Generating": "生成中",
  "Artifacts are files the agent creates during a conversation to help perform longer running tasks and allow the user to provide high-level feedback. Click to open in editor.": "产物是 Agent 在对话中创建的文件，用于帮助执行较长时间运行的任务并允许用户提供高级反馈。点击在编辑器中打开。",
  "Artifact Name": "产物名称",
  "Last Updated": "最后更新",
  "Send": "发送",
  "Audio is not supported for this model": "该模型不支持音频",
  "No microphone detected": "未检测到麦克风",
  "Comment": "评论",
  "Reject": "拒绝",
  "result": "个结果",
  "Always Ask": "始终询问",
  "Select one of the": "从",
  "Agent security mode": "Agent 安全模式",
  "Full access": "完全访问",
  "Agents have full access to your machine and external resources.": "Agent 可以完全访问您的计算机和外部资源。",
  "Sandboxed": "沙盒化",
  "Agents run in a secure sandbox that restricts access to external resources outside of your trusted folders.": "Agent 运行在安全的沙盒中，限制访问信任文件夹以外的外部资源。",
  "Strict": "严格",
  "Terminal commands always require review and the agent cannot access files outside of its given workspaces.": "终端命令始终需要审查，且 Agent 无法访问指定工作区以外的文件。",
  "Enable Shell Integration": "启用 Shell 集成",
  "File Access": "文件访问",
  "Allows the agent to access files outside of your current workspace.": "允许 Agent 访问当前工作区以外的文件。",
  "Planning": "规划",
  "Automation": "自动化",
  "History": "历史记录",
  "General": "常规",
  "Explain and Fix in Current Conversation": "在当前对话中解释和修复",
  "Advanced": "高级",
  "Advanced File Access": "高级文件访问",
  "Read Files": "读取文件",
  "Write Files": "写入文件",
  "Advanced Command Access": "高级命令访问",
  "Terminal Commands": "终端命令",
  "Commands Outside Sandbox": "沙盒外的命令",
  "MCP Tools": "MCP 工具",
  "Advanced Web Access": "高级网络访问",
  "Read URLs": "读取 URL",
  "Execute URLs": "执行 URL",
  "Advanced Settings": "高级设置",
  "Enable Demo Mode (Beta)": "启用演示模式 (Beta)",
  "When toggled on, ${r.product.nameShort} collects usage data to help Google enhance performance and features.": "开启后，${r.product.nameShort} 将收集使用数据，以帮助 Google 提升性能和功能。",
  "Marketing Emails": "营销邮件",
  "By using this app, you agree to its": "使用此应用即表示您同意其",
  "Terms of Service": "服务条款",
  "Terms of Service & Data Use": "服务条款与数据使用",
  "Configure the browser subagent. It requires": "配置浏览器子 Agent。它需要安装",
  "View your available model quota. Quota refreshes periodically based on your plan.": "查看您可用的模型配额。配额会根据您的方案定期刷新。",
  "% of the customization budget is available.": "% 的定制预算当前可用。",
  "Hide breakdown": "隐藏明细",
  "Plugin:": "插件:",
  "Plugins are packaged collections of skills and MCPs to help the Agent": "插件是技能和 MCP 的打包集合，用于帮助 Agent",
  "Plugins are packaged collections of skills and MCPs to help the Agent in": "插件是技能和 MCP 的打包集合，用于帮助 Agent 在",
  "No MCP Servers": "没有 MCP 服务器",
  "Account": "账户",
  "Notifications": "通知",
  "Models": "模型",
  "Customizations": "自定义",
  "Browser Settings": "浏览器设置",
  "Account & Plan": "账户与方案",
  "Email": "电子邮件",
  "Theme": "主题",
  "Chat Settings": "聊天设置",
  "Verbose agent chat": "详细 Agent 聊天",
  "Model Quota": "模型配额",
  "Actuation Permissions": "执行操作权限",
  "Browser Actuation Rules": "浏览器执行规则",
  "Marketplace": "市场",
  "Changes the base URL on each extension page. You must restart Antigravity IDE to use the new marketplace after changing this value.": "更改每个扩展页面的基础 URL。更改此值后，您必须重启 Antigravity IDE 才能使用新的市场。",
  "Changes the base URL for marketplace search results. You must restart Antigravity IDE to use the new marketplace after changing this value.": "更改市场搜索结果的基础 URL。更改此值后，您必须重启 Antigravity IDE 才能使用新的市场。",
  "Selection Actions": "选中操作",
  "MCP Servers": "MCP 服务器",
  "Manage MCP Servers": "管理 MCP 服务器",
  "Rules": "规则",
  "Workflows": "工作流",
  "Rules help guide the behavior of Agent.": "规则可以帮助引导 Agent 的行为。",
  "Edit rule": "编辑规则",
  "Edit workflow": "编辑工作流",
  "Refresh rules": "刷新规则",
  "Refresh workflows": "刷新工作流",
  "Mentions": "提及",
  "Screen Recording": "屏幕录制",
  "Back to Agent": "返回 Agent",
  "Close Agent View": "关闭 Agent 视图",
  "Past Conversations": "历史对话",
  "Connect to an existing conversation": "连接到现有对话",
  "Cancel": "取消",
  "Cancel command": "取消命令",
  "Cancel step": "取消步骤",
  "Confirm": "确认",
  "Confirm Undo": "确认撤销",
  "Create": "创建",
  "Delete": "删除",
  "Dismiss": "忽略",
  "Expand": "展开",
  "Install": "安装",
  "Launch": "启动",
  "Open": "打开",
  "Preview": "预览",
  "Refresh": "刷新",
  "Retry": "重试",
  "Review": "审查",
  "Review Changes": "审查更改",
  "Save": "保存",
  "Send Feedback": "发送反馈",
  "See all": "查看全部",
  "Show more": "显示更多",
  "Continue response": "继续响应",
  "Configure": "配置",
  "Configure Auto-Continue": "配置自动继续",
  "Next": "下一步",
  "Previous": "上一步",
  "Reload IDE": "重新加载 IDE",
  "Clear": "清除",
  "Setup": "设置",
  "New": "新建",
  "Default": "默认",
  "Custom": "自定义",
  "Copy command": "复制命令",
  "Copy diff": "复制差异",
  "Copy the trajectory ID": "复制轨迹 ID",
  "Open diff": "打开差异",
  "Open in New Window": "在新窗口中打开",
  "Open allowlist": "打开允许列表",
  "Start Screen Recording": "开始屏幕录制",
  "Set Browser Config": "设置浏览器配置",
  "View Diff": "查看差异",
  "View Page": "查看页面",
  "View network request": "查看网络请求",
  "View network requests": "查看网络请求",
  "View plans": "查看计划",
  "View Annotation": "查看注释",
  "View Created Links": "查看已创建链接",
  "View snapshot": "查看快照",
  "Thinking": "思考中",
  "Analyzed": "已分析",
  "Installed": "已安装",
  "Error": "错误",
  "Something went wrong": "出了点问题",
  "An error was thrown.": "发生了一个错误。",
  "Failed to send": "发送失败",
  "Launching the browser...": "正在启动浏览器...",
  "Playback available": "可以回放",
  "Preview unavailable": "预览不可用",
  "No matching results": "没有匹配的结果",
  "No results": "无结果",
  "No results found": "未找到结果",
  "No results found.": "未找到结果。",
  "No browser pages open": "没有打开的浏览器页面",
  "Loading MCP servers": "正在加载 MCP 服务器",
  "Reconnecting to remote authority.": "正在重新连接到远程服务器。",
  "Disabled in strict mode": "在严格模式下已禁用",
  "Full output written to": "完整输出已写入",
  "Read URL rejected": "读取 URL 被拒绝",
  "Rejected MCP tool": "已拒绝 MCP 工具",
  "Proceeded with": "已继续执行",
  "Unknown edit": "未知编辑",
  "Unknown file edit": "未知文件编辑",
  "Built-In": "内置",
  "Authentication Required": "需要身份验证",
  "Confirmation required to execute this step": "执行此步骤需要确认",
  "Antigravity would like to use the browser.": "Antigravity 希望使用浏览器。",
  "The Agent attempted to interact with some sites that are not allowlisted": "Agent 尝试与一些不在允许列表中的网站交互",
  "The agent was prevented from accessing some sites": "Agent 已被阻止访问某些网站",
  "The agent will wait for you to install the browser extension.": "Agent 将等待你安装浏览器扩展。",
  "This plugin has been built by a verified reference publisher.": "此插件由经过验证的参考发布者构建。",
  "This plugin has been built by the official publisher.": "此插件由官方发布者构建。",
  "Read URL content?": "读取 URL 内容？",
  "Run MCP tool call?": "运行 MCP 工具调用？",
  "Modify the config used for browser interactions. Saved automatically.": "修改用于浏览器交互的配置。自动保存。",
  "After reporting the issue, reload your window to resume Agent use.": "报告问题后，重新加载窗口以恢复 Agent 使用。",
  "Files results show if their associated language extension is installed.": "文件结果会在安装了关联的语言扩展后显示。",
  "Select a trajectory": "选择一个轨迹",
  "Sources": "来源",
  "Details": "详细信息",
  "Features": "功能",
  "Comments": "评论",
  "Images": "图片",
  "Files Edited": "已编辑文件",
  "Background Steps": "后台步骤",
  "Suggested Actions": "建议操作",
  "Progress Updates": "进度更新",
  "Pending messages": "待处理消息",
  "Knowledge Generation": "知识生成",
  "Recent actions": "最近操作",
  "Report Issue": "报告问题",
  "Conversation": "对话",
  "Additional options": "其他选项",
  "Feedback": "反馈",
  "Denied Sites": "被拒绝的网站",
  "Global": "全局",
  "MCP Store": "MCP 商店",
  "Good": "好",
  "Bad": "差",
  "Good response": "好的响应",
  "Bad response": "差的响应",
  "Open System Browser": "打开系统浏览器",
  "Fetched network request for page.": "已获取页面的网络请求。",
  "Fetched network requests for page.": "已获取页面的网络请求。",
  "Complete verification": "完成验证",
  "Copy": "复制",
  "Paste": "粘贴",
  "Export": "导出",
  "Enable": "启用",
  "Try again": "再试一次",
  "Deny": "拒绝",
  "Allow Once": "允许一次",
  "Always Allow": "始终允许",
  "Always run": "始终运行",
  "Ask every time": "每次询问",
  "Ask first": "先询问",
  "Download Diagnostics": "下载诊断信息",
  "Copy debug info": "复制调试信息",
  "Select Model": "选择模型",
  "Select another model": "选择其他模型",
  "Terminal": "终端命令",
  "Media": "媒体",
  "Errors": "错误",
  "Workspace": "工作区",
  "Free": "免费",
  "Verification required": "需要验证",
  "Share Conversation": "分享对话",
  "Enable Notifications": "启用通知",
  "Select Model to Send Message": "选择模型以发送消息",
  "Model quota limit exceeded": "模型配额已超限",
  "Capture screenshot": "截取屏幕",
  "Capture console logs": "捕获控制台日志",
  "Confirm dismiss?": "确认忽略？",
  "Could not send message": "无法发送消息",
  "Your modified files:": "你修改的文件：",
  "Your recent Browser activity:": "你最近的浏览器活动：",
  "Your recent terminal commands:": "你最近的终端命令：",
  "Mention Page": "提及页面",
  "Full Error": "完整错误",
  "First page": "第一页",
  "Last page": "最后一页",
  "Next page": "下一页",
  "Previous page": "上一页",
  "Copy full URL to clipboard": "复制完整 URL 到剪贴板",
  "Click to copy full command": "点击复制完整命令",
  "Copy trajectory ID": "复制轨迹 ID",
  "Search MCP servers": "搜索 MCP 服务器",
  "Go to Terminal": "前往终端",
  "Relocate": "重新定位",
  "Allow This Conversation": "本次对话允许",
  "Reject all": "全部拒绝",
  "Learn more": "了解更多",
  "file an issue": "提交问题",
  "reload the window": "重新加载窗口",
  "troubleshooting guide": "故障排除指南",
  "Show items analyzed": "显示已分析项目",
  "Added Annotation": "已添加注释",
  "Start a New Conversation": "开始新对话",
  "Manually set Agent ID": "手动设置 Agent ID",
  "Search metrics...": "搜索指标...",
  "Find": "查找",
  "AI may make mistakes. Double-check all generated code.": "AI 可能会犯错。请仔细检查所有生成的代码。",
  "1. Report Issue": "1. 报告问题",
  "Get Logs": "获取日志",
  "If you are having difficulty using": "如果你在使用",
  ", please report the issue using our feedback form.": "时遇到困难，请使用我们的反馈表单报告问题。",
  ". As always, you can use the thumbs up or thumbs down feedback mechanism to help improve our metrics.": "。您可以使用点赞或点踩反馈机制来帮助改进我们的指标。",
  "(Dev-only) Select a mixin to use in the agent. This will tailor Cascade for different task types by changing things like the system prompt, tools available, etc.": "(仅开发) 选择要在代理中使用的混入。这将通过更改系统提示、可用工具等来为不同的任务类型定制 Cascade。",
  "[Today at] LT": "[今天] LT",
  "[Tomorrow at] LT": "[明天] LT",
  "[Yesterday at] LT": "[昨天] LT",
  "%d days": "%d 天",
  "%d hours": "%d 小时",
  "%d minutes": "%d 分钟",
  "%d months": "%d 个月",
  "%d seconds": "%d 秒",
  "%d weeks": "%d 周",
  "%d years": "%d 年",
  "%s ago": "%s前",
  "2. Resetting Agent": "2. 重置代理",
  "A chunk is a section of the page. Long pages are chunked so that only the sections that are relevant to your query are read.": "块是页面的一个部分。长页面会被分块，以便只读取与您的查询相关的部分。",
  "a day": "一天",
  "a few seconds": "几秒",
  "a minute": "一分钟",
  "a month": "一个月",
  "a week": "一周",
  "a year": "一年",
  "Aborted": "已中止",
  "Absolute uri to pbtxt config": "pbtxt 配置的绝对 URI",
  "Accepted": "已接受",
  "Accessibility": "辅助功能",
  "Active Browser page": "活动浏览器页面",
  "Active Browser pages": "活动浏览器页面",
  "Active": "活动",
  "Activities cannot be viewed": "无法查看活动",
  "Activity": "活动",
  "Agent Action DOM Diffs:": "代理操作 DOM 差异:",
  "Agent can click and drag in the browser.": "代理可以在浏览器中点击和拖动。",
  "Agent can click on specific elements in the browser.": "代理可以点击浏览器中的特定元素。",
  "Agent can resize browser windows to different dimensions or window states.": "代理可以将浏览器窗口调整为不同的尺寸或窗口状态。",
  "Agent execution terminated due to model provider overload. Please try again later.": "代理执行因模型提供商过载而终止。请稍后重试。",
  "Agent terminated due to error": "代理因错误而终止",
  "Allow once": "允许一次",
  "Already exists": "已存在",
  "Alt text:": "替代文本:",
  "Always allow": "始终允许",
  "Always ask for permission": "始终询问权限",
  "Always Auto-Run": "始终自动运行",
  "Always run terminal commands": "始终运行终端命令",
  "An error ID that helps the team investigate the error.": "帮助团队调查错误的错误 ID。",
  "an hour": "一小时",
  "An unknown error occurred": "发生未知错误",
  "Approved": "已批准",
  "Argument must be a Buffer": "参数必须是 Buffer",
  "Arguments Schema:": "参数模式:",
  "Artifact Comments": "工件评论",
  "Artifact image": "工件图像",
  "Artifacts are created when the agent performs more complex, longer running tasks while in Planning mode.": "工件是代理在规划模式下执行更复杂、耗时更长的任务时创建的。",
  "At mention": "@ 引用",
  "Attach the trajectory ID to the feedback form": "将轨迹 ID 附加到反馈表单",
  "Attempt to write outside buffer bounds": "尝试写入缓冲区边界外",
  "Attribute": "属性",
  "Authorization": "授权",
  "Auto-Run On Model Decision": "根据模型决策自动运行",
  "Back to content": "返回内容",
  "background terminal command": "后台终端命令",
  "Backwards": "向后",
  "Baseline": "基线",
  "BETA": "测试版",
  "Billed at API pricing": "按 API 定价计费",
  "Browser Code": "浏览器代码",
  "Browser Content": "浏览器内容",
  "Browser Mode:": "浏览器模式:",
  "Browser Text": "浏览器文本",
  "Browser Tool Set Mode:": "浏览器工具集模式:",
  "Browser Tools:": "浏览器工具:",
  "Bytes": "字节",
  "Canceled creation of": "已取消创建",
  "Canceled deletion of": "已取消删除",
  "Canceled edit to": "已取消编辑",
  "Canceled extension code": "已取消扩展代码",
  "Canceled": "已取消",
  "Cannot revert messages with artifact comments": "无法撤销包含工件评论的消息",
  "Cannot revert messages with file comments": "无法撤销包含文件评论的消息",
  "Cannot revert messages with file diff comments": "无法撤销包含文件差异评论的消息",
  "Cannot revert this message": "无法撤销此消息",
  "Caps Lock": "大写锁定",
  "Chat Model Metadata": "聊天模型元数据",
  "Checked command status": "已检查命令状态",
  "Checking command status": "正在检查命令状态",
  "Clear NUX state": "清除新用户状态",
  "Cleared Count": "已清除计数",
  "Click Feedback:": "点击反馈:",
  "Clicked in Browser": "在浏览器中点击",
  "Clicked": "已点击",
  "Clicking in Browser": "正在浏览器中点击",
  "Clicking": "点击中",
  "Closed": "已关闭",
  "Closing": "关闭中",
  "Code Context Item Subranges": "代码上下文子范围",
  "Code Context Items": "代码上下文项",
  "Files": "文件",
  "MCP servers": "MCP 服务器",
  "Conversations": "聊天列表",
  "Code Snippet": "代码片段",
  "Combobox": "组合框",
  "Configure Auto-Run": "配置自动运行",
  "Confirm Browser Interaction": "确认浏览器交互",
  "Confirming this undo action will make the following changes:": "确认此撤销操作将进行以下更改:",
  "Console Logs": "控制台日志",
  "Conversational": "对话式",
  "Coordinated Universal Time": "协调世界时",
  "Copied": "已复制",
  "Copy Link": "复制链接",
  "Copy to clipboard": "复制到剪贴板",
  "Cost": "成本",
  "Created At": "创建时间",
  "Created:": "创建于:",
  "Creating": "创建中",
  "Custom Config": "自定义配置",
  "Custom models are only supported on Cloudtop / Linux machines.": "自定义模型仅在 Cloudtop / Linux 机器上支持。",
  "Custom Reminder:": "自定义提醒:",
  "Custom URI": "自定义 URI",
  "Data loss": "数据丢失",
  "Dead": "已终止",
  "Deadline exceeded": "超时",
  "Debug Mode": "调试模式",
  "Debug Sidebar": "调试侧边栏",
  "Default Config": "默认配置",
  "Deleted": "已删除",
  "Deleting": "删除中",
  "Description:": "描述:",
  "Description": "描述",
  "Developer Menu": "开发者菜单",
  "Dialog": "对话框",
  "Diameter": "直径",
  "Directories": "目录",
  "Disabled in Secure Mode": "在安全模式下已禁用",
  "Disclosure": "披露",
  "Dismiss suggested actions": "关闭建议操作",
  "Document Answers": "文档答案",
  "DOM Element": "DOM 元素",
  "Dragged in Browser": "在浏览器中拖拽",
  "Dragging in Browser": "正在浏览器中拖拽",
  "Dynamic Wait Tool:": "动态等待工具:",
  "Editing": "编辑中",
  "Electron Mode": "Electron 模式",
  "Empty": "空",
  "Enabled": "已启用",
  "End of comment missing": "缺少注释结尾",
  "Enlarged image": "放大的图像",
  "Enter Agent ID": "输入代理 ID",
  "Enter custom reminder text for the planner...": "输入规划器的自定义提醒文本...",
  "Ephemeral Options:": "临时选项:",
  "Equal": "相等",
  "Error checking microphone availability:": "检查麦克风可用性时出错:",
  "Error Details:": "错误详情:",
  "Error Details": "错误详情",
  "Error during tool execution": "工具执行期间出错",
  "Error editing file": "编辑文件时出错",
  "Error in event listener:": "事件监听器出错:",
  "Error occurred": "发生错误",
  "Error opening workspace quick pick:": "打开工作区快速选择时出错:",
  "Error parsing JSON:": "解析 JSON 时出错:",
  "Error rendering CodeBlock": "渲染代码块时出错",
  "Error rendering Markdown": "渲染 Markdown 时出错",
  "Error rendering playback": "渲染回放时出错",
  "Error viewing file": "查看文件时出错",
  "Error while analyzing directory": "分析目录时出错",
  "Error while editing": "编辑时出错",
  "Error while running command": "运行命令时出错",
  "Error while running MCP tool": "运行 MCP 工具时出错",
  "Error while searching filesystem": "搜索文件系统时出错",
  "Error while searching the web": "搜索网页时出错",
  "Error while searching": "搜索时出错",
  "Error while semantic searching": "语义搜索时出错",
  "Error while viewing": "查看时出错",
  "Execute Javascript policy": "执行 JavaScript 策略",
  "Expected a function": "期望一个函数",
  "Expected a string": "期望一个字符串",
  "Expected array or object as schema": "期望数组或对象作为架构",
  "Expected character": "期望字符",
  "Expected substring": "期望子字符串",
  "Extension client not available": "扩展客户端不可用",
  "Extracted DOM elements": "已提取 DOM 元素",
  "Extracting DOM elements": "正在提取 DOM 元素",
  "Failed precondition": "前置条件失败",
  "Failed to add URL to allowlist: addToBrowserAllowlist is undefined": "添加 URL 到白名单失败: addToBrowserAllowlist 未定义",
  "Failed to add URL to allowlist:": "添加 URL 到白名单失败:",
  "Failed to copy text using Clipboard API:": "使用剪贴板 API 复制文本失败:",
  "Failed to copy text using document.execCommand:": "使用 document.execCommand 复制文本失败:",
  "Failed to create workflow:": "创建工作流失败:",
  "Failed to delete queued message:": "删除排队消息失败:",
  "Failed to enable server, click to see details.": "启用服务器失败，点击查看详情。",
  "Failed to extract waveform:": "提取波形失败:",
  "Failed to fetch custom agent configs:": "获取自定义代理配置失败:",
  "failed to fetch HEAD for": "获取 HEAD 失败:",
  "Failed to find the root element": "未能找到根元素",
  "Failed to get static experiments": "获取静态实验失败",
  "Failed to open plugin page:": "打开插件页面失败:",
  "Failed to parse ContextScopeItem from mention node:": "从提及节点解析 ContextScopeItem 失败:",
  "Failed to parse quota metadata": "解析配额元数据失败",
  "Failed to parse quota reset timestamp": "解析配额重置时间戳失败",
  "Failed to parse tool JSON schema:": "解析工具 JSON 模式失败:",
  "Failed to parse toolCallArgumentsJson:": "解析 toolCallArgumentsJson 失败:",
  "Failed to refresh user memories:": "刷新用户记忆失败:",
  "Failed to start screen recording": "启动屏幕录制失败",
  "File Comments": "文件评论",
  "File Diff Comments": "文件差异评论",
  "Files to edit:": "要编辑的文件:",
  "First argument must be a string": "第一个参数必须是字符串",
  "Focus": "聚焦",
  "Focused": "已聚焦",
  "Folder": "文件夹",
  "Folders": "文件夹",
  "Footnotes": "脚注",
  "Forward": "前进",
  "Forwards": "向前",
  "Found references to": "找到引用",
  "Fragment": "片段",
  "Full Metadata": "完整元数据",
  "Gemini Computer Use": "Gemini 计算机使用",
  "Generated image preview": "生成的图像预览",
  "Generating extension code": "正在生成扩展代码",
  "Goal": "目标",
  "Greater": "大于",
  "Hashing function not available": "哈希函数不可用",
  "Heading": "标题",
  "Hidden": "已隐藏",
  "Hide 0s": "隐藏 0 秒",
  "Hours": "小时",
  "I did": "已完成",
  "If you believe this is a bug, please": "如果您认为这是一个 bug，请",
  "Ignore warning and attempt to send messages anyway regardless of network connection status. As a result, messages may get dropped.": "忽略警告并尝试发送消息，无论网络连接状态如何。因此，消息可能会丢失。",
  "Image Answers": "图像答案",
  "Image Diff Not Supported": "不支持图像差异",
  "Image rendering blocked (Secure Mode enabled)": "图像渲染被阻止 (安全模式已启用)",
  "Image URL:": "图像 URL:",
  "in %s": "%s后",
  "In progress": "进行中",
  "Index out of range": "索引超出范围",
  "Initializing": "初始化中",
  "Input": "输入",
  "Insert in terminal": "插入到终端",
  "Inspected commit": "已检查的提交",
  "Internal": "内部",
  "Invalid argument": "无效参数",
  "Invalid code point": "无效的代码点",
  "Invalid date": "无效日期",
  "Invalid metadata page": "无效的元数据页面",
  "Invalid time value": "无效的时间值",
  "Invariant Violation": "不变量违规",
  "JavaScript Result": "JavaScript 结果",
  "Jumps to the location of the terminal session that ran this command.": "跳转到运行此命令的终端会话位置。",
  "Language server client not available": "语言服务器客户端不可用",
  "Legacy": "旧版",
  "Less": "小于",
  "Line Ranges": "行范围",
  "List resources:": "列出资源:",
  "Listbox": "列表框",
  "LLMs can generate incorrect responses that we cannot handle.": "LLM 可能生成我们无法处理的错误响应。",
  "Malformed diff information": "差异信息格式错误",
  "Manually Captured": "手动捕获",
  "Manually Rejected": "手动拒绝",
  "Max Context Characters (optional):": "最大上下文字符数 (可选):",
  "Max Tokens": "最大 Token 数",
  "MCP Tool:": "MCP 工具:",
  "Metadata:": "元数据:",
  "Metadata": "元数据",
  "Metric": "指标",
  "Milliseconds": "毫秒",
  "Minutes": "分钟",
  "Missing chat params context": "缺少聊天参数上下文",
  "Mixins": "混入",
  "Model Label": "模型标签",
  "Model URL": "模型 URL",
  "Month": "月",
  "Move Mouse in Browser": "在浏览器中移动鼠标",
  "Move": "移动",
  "Moves this terminal session to the Terminal tab in your IDE. The agent will still be able to use it.": "将此终端会话移动到 IDE 的终端选项卡。代理仍可以使用它。",
  "Moving Mouse in Browser": "正在浏览器中移动鼠标",
  "Never Auto-Run": "从不自动运行",
  "No @-mention results": "无 @ 引用结果",
  "No chat model metadata available for this generator": "此生成器无可用的聊天模型元数据",
  "No chat model metadata available in latest generator metadata": "最新生成器元数据中无可用的聊天模型元数据",
  "No content available for this resource": "此资源无可用内容",
  "No credits used": "未使用积分",
  "No description": "无描述",
  "No generator metadata available": "无可用的生成器元数据",
  "No Javascript Result Output": "无 JavaScript 结果输出",
  "No message prompts available": "无可用的消息提示",
  "No Model Selected": "未选择模型",
  "No renderer found for step case": "未找到步骤渲染器",
  "No resources available": "无可用资源",
  "No response from extension client": "扩展客户端无响应",
  "No screenshot returned from captureScreenshot RPC": "captureScreenshot RPC 未返回截图",
  "No snapshot taken": "未拍摄快照",
  "No step index found for artifact code action step": "未找到工件代码操作步骤的步骤索引",
  "No step index found for code action step": "未找到代码操作步骤的步骤索引",
  "No trajectories available": "无可用轨迹",
  "No trajectory steps available": "无可用轨迹步骤",
  "No trajectory": "无轨迹",
  "No URL returned from server": "服务器未返回 URL",
  "No versions available": "无可用版本",
  "None": "无",
  "Not a redirect error": "不是重定向错误",
  "Not implemented": "未实现",
  "Nothing": "无",
  "Open extracted DOM tree in editor": "在编辑器中打开提取的 DOM 树",
  "Open in Terminal": "在终端中打开",
  "Open PLX dashboard for metadata index": "打开元数据索引的 PLX 仪表板",
  "Open Trajectory Dashboard": "打开轨迹仪表板",
  "Opened URL in Browser": "已在浏览器中打开 URL",
  "Opening URL in Browser": "正在浏览器中打开 URL",
  "Opening": "打开中",
  "Opens the associated terminal session in the Terminal tab in your IDE.": "在 IDE 的终端选项卡中打开关联的终端会话。",
  "Out of range index": "索引超出范围",
  "Out of range": "超出范围",
  "Output": "输出",
  "Overflow": "溢出",
  "Page contents": "页面内容",
  "Parentheses": "圆括号",
  "Parser was already resumed": "解析器已恢复",
  "Paste or type ID here": "在此粘贴或输入 ID",
  "Pending comments": "待处理评论",
  "Permission denied": "权限被拒绝",
  "Pressed": "已按下",
  "Pressing": "按下中",
  "Processing": "处理中",
  "Profiler": "分析器",
  "Radius:": "半径:",
  "Ran extension code": "已运行扩展代码",
  "Read Browser Page in Browser": "在浏览器中读取页面",
  "Read page": "读取页面",
  "Read resource:": "读取资源:",
  "Reading Browser Page in Browser": "正在浏览器中读取页面",
  "Reading page": "正在读取页面",
  "Reading": "读取中",
  "Ready": "就绪",
  "Recommended": "推荐",
  "Record voice memo": "录制语音备忘",
  "Reference": "引用",
  "Refresh Custom Agent Configs": "刷新自定义代理配置",
  "Refresh trajectory list": "刷新轨迹列表",
  "Rejected extension code": "已拒绝扩展代码",
  "Remove audio": "移除音频",
  "Rendered Step:": "渲染步骤:",
  "Rendering playback": "渲染回放",
  "Repositories": "仓库",
  "Requested changes": "请求的更改",
  "Resized Browser window": "已调整浏览器窗口大小",
  "Resizing Browser window": "正在调整浏览器窗口大小",
  "Resource exhausted": "资源耗尽",
  "Retrieved Browser Pages": "已获取浏览器页面",
  "Retrieved Console Logs from Browser": "已从浏览器获取控制台日志",
  "Retrieved": "已获取",
  "Retrieving Browser Pages": "正在获取浏览器页面",
  "Retrieving Console Logs from Browser": "正在从浏览器获取控制台日志",
  "Retrieving": "获取中",
  "Right": "右",
  "Run code?": "运行代码?",
  "Run command?": "运行命令?",
  "Run extension code": "运行扩展代码",
  "Running extension code": "正在运行扩展代码",
  "Scroll to bottom": "滚动到底部",
  "Scrolled down in Browser": "在浏览器中向下滚动",
  "Scrolled in Browser": "在浏览器中滚动",
  "Scrolled up in Browser": "在浏览器中向上滚动",
  "Scrolled": "已滚动",
  "Scrolling down in Browser": "正在浏览器中向下滚动",
  "Scrolling in Browser": "正在浏览器中滚动",
  "Scrolling up in Browser": "正在浏览器中向上滚动",
  "Searched": "已搜索",
  "Searching": "搜索中",
  "Seconds": "秒",
  "Sections": "部分",
  "See our": "查看我们的",
  "See plans": "查看方案",
  "Segment Metrics": "分段指标",
  "Select a model using the model selector in the input box": "使用输入框中的模型选择器选择模型",
  "Select from known": "从已知中选择",
  "Select Model:": "选择模型:",
  "Select Option in Browser": "在浏览器中选择选项",
  "Select option": "选择选项",
  "Selecting Option in Browser": "正在浏览器中选择选项",
  "Semantic searched": "已语义搜索",
  "Semantic searching": "语义搜索中",
  "Send feedback": "发送反馈",
  "Shapes": "形状",
  "Sheet": "表格",
  "Sherlog Links": "Sherlog 链接",
  "Show 0s": "显示 0 秒",
  "Show all resources": "显示所有资源",
  "Show allowlist": "显示允许列表",
  "Show fewer resources": "显示较少资源",
  "Show less": "显示更少",
  "Show page allowlist": "显示页面允许列表",
  "Simulated Key Press in Browser": "在浏览器中模拟按键",
  "Simulating Key Press in Browser": "正在浏览器中模拟按键",
  "Site Allowlist": "网站允许列表",
  "Some non-image binary content was truncated.": "部分非图像二进制内容已被截断。",
  "Source:": "来源:",
  "Step handler not available": "步骤处理程序不可用",
  "Step JSON:": "步骤 JSON:",
  "Step Type": "步骤类型",
  "Step:": "步骤:",
  "Stop recording": "停止录制",
  "Subagent Context Mode:": "子代理上下文模式:",
  "Subagent Reminder Mode:": "子代理提醒模式:",
  "System Message": "系统消息",
  "Take trajectory snapshot": "拍摄轨迹快照",
  "Taking Screenshot": "正在截图",
  "Terminal command": "终端命令",
  "This operation was aborted": "此操作已中止",
  "This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.": "此浏览器缺少 `buffer` v5.x 所需的类型化数组 (Uint8Array) 支持。如果需要旧浏览器支持，请使用 `buffer` v4.x。",
  "To provide feedback": "提供反馈",
  "Toggle Debug Mode": "切换调试模式",
  "Toggle Debug Sidebar": "切换调试侧边栏",
  "Toggle Dev View": "切换开发视图",
  "Toggle Ephemeral Messages": "切换临时消息",
  "Toggle Incognito Mode": "切换无痕模式",
  "Took Screenshot": "已截图",
  "Tool Calls": "工具调用",
  "Trajectory ID": "轨迹 ID",
  "Trajectory Metrics": "轨迹指标",
  "Trajectory Snapshot": "轨迹快照",
  "Trajectory Stats": "轨迹统计",
  "Trigger must be a single character": "触发器必须是单个字符",
  "Trigger must be one character long": "触发器长度必须为一个字符",
  "Trying to access beyond buffer length": "尝试访问超出缓冲区长度",
  "Type into Browser": "在浏览器中输入",
  "Typeahead menu": "自动完成菜单",
  "Typing into Browser": "正在浏览器中输入",
  "Unauthenticated": "未认证",
  "Unavailable": "不可用",
  "Underflow": "下溢",
  "Undo changes up to this point": "撤销到此处的更改",
  "Unexpected undefined": "意外的未定义",
  "Unidentified": "未识别",
  "Unimplemented": "未实现",
  "Unknown error fetching browser pages": "获取浏览器页面时发生未知错误",
  "Unknown error occurred": "发生未知错误",
  "Unknown error": "未知错误",
  "Unknown path": "未知路径",
  "Unknown quota limit error reason": "未知配额限制错误原因",
  "Unknown state": "未知状态",
  "Unmount": "卸载",
  "Unnamed resource": "未命名资源",
  "Unsupported browser target": "不支持的浏览器目标",
  "untitled": "未命名",
  "Upload to Agent": "上传到代理",
  "Upload": "上传",
  "User Implicit Trajectories": "用户隐式轨迹",
  "User Implicit": "用户隐式",
  "User uploaded image": "用户上传的图像",
  "Users": "用户",
  "Uses your API key": "使用您的 API 密钥",
  "Value": "值",
  "Visible only": "仅可见",
  "Wait for": "等待",
  "Waiting": "等待中",
  "When debug mode is on, you can see additional information about each steps in the conversation.": "开启调试模式后，您可以查看对话中每个步骤的额外信息。",
  "With Markdown Trajectory Summary": "包含 Markdown 轨迹摘要",
  "Unleash failed to resolve \\": "Unleash 无法解析 \\",
  "Unleash: You must either provide your own \\": "Unleash: 您必须提供自己的 \\",
  "Unleash SDK has already started, if you want to restart the SDK you should call client.stop() before starting again.": "Unleash SDK 已启动，如果要重新启动 SDK，应先调用 client.stop()。",
  "Unleash: Fetching feature toggles did not have an ok response": "Unleash: 获取功能开关未收到正常响应",
  "Unleash: unable to fetch feature toggles": "Unleash: 无法获取功能开关",
  "Unleash: unable to send feature metrics": "Unleash: 无法发送功能指标",
  "on() must be used within a FlagProvider": "on() 必须在 FlagProvider 中使用",
  "off() must be used within a FlagProvider": "off() 必须在 FlagProvider 中使用",
  "updateContext() must be used within a FlagProvider": "updateContext() 必须在 FlagProvider 中使用",
  "isEnabled() must be used within a FlagProvider": "isEnabled() 必须在 FlagProvider 中使用",
  "getVariant() must be used within a FlagProvider": "getVariant() 必须在 FlagProvider 中使用",
  "useOnSendMessageContext must be used within an OnSendMessageContextProvider": "useOnSendMessageContext 必须在 OnSendMessageContextProvider 中使用",
  "Failed to update conversation annotations:": "更新对话注释失败:",
  "Auto Agent not supported at GDM (yet)": "GDM 暂不支持自动代理",
  "Failed to send message": "发送消息失败",
  "Error fetching model statuses:": "获取模型状态时出错:",
  "Exception in backgroundFetchModelStatuses:": "backgroundFetchModelStatuses 中发生异常:",
  "Failed to fetch user status:": "获取用户状态失败:",
  "[Paste Interceptor] No selection found": "[粘贴拦截器] 未找到选择内容",
  "No trigger was found for the editor": "未找到编辑器的触发器",
  "Error fetching workflows:": "获取工作流时出错:",
  "Error fetching rules:": "获取规则时出错:",
  "Error listing MCP resources:": "列出 MCP 资源时出错:",
  "Error listing terminals:": "列出终端时出错:",
  "Error listing MCP server names:": "列出 MCP 服务器名称时出错:",
  "Failed to open Review Changes:": "打开审查更改失败:",
  "Failed to get workspace infos:": "获取工作区信息失败:",
  "Failed to export conversation:": "导出对话失败:",
  "Error fetching MCP servers:": "获取 MCP 服务器时出错:",
  "Error: unable to parse context item": "错误: 无法解析上下文项",
  "Error in connection error handler:": "连接错误处理程序中出错:",
  "Unknown request case:": "未知请求类型:",
  "Unexpected error starting chat client server stream:": "启动聊天客户端服务器流时发生意外错误:",
  "Chat client server stream canceled by original abort signal": "聊天客户端服务器流被原始中止信号取消",
  "Error starting chat client server stream:": "启动聊天客户端服务器流时出错:",
  "Failed to update user settings:": "更新用户设置失败:",
  "Error sharing trajectory:": "分享轨迹时出错:",
  "forceFrameRate takes a positive int between 0 and 125, forcing frame rates higher than 125 fps is not supported": "forceFrameRate 接受 0 到 125 之间的正整数，不支持强制帧率高于 125 fps",
  "A component is changing from controlled to uncontrolled. This may be caused by the value changing from a defined value to undefined, which should not happen.": "组件正在从受控变为非受控。这可能是由于值从已定义变为 undefined，这不应该发生。",
  "A component is changing from uncontrolled to controlled. This may be caused by the value changing from undefined to a defined value, which should not happen.": "组件正在从非受控变为受控。这可能是由于值从 undefined 变为已定义值，这不应该发生。",
  "Nonretryable error starting chat client server stream:": "启动聊天客户端服务器流时发生不可重试错误:",
  "Error copying to clipboard:": "复制到剪贴板时出错:",
  "Failed to capture browser console logs: No console logs found": "捕获浏览器控制台日志失败: 未找到控制台日志",
  "Failed to capture browser console logs:": "捕获浏览器控制台日志失败:",
  "Failed to capture screenshot:": "捕获截图失败:",
  "Failed to fetch revert preview:": "获取还原预览失败:",
  "Error opening MCP page:": "打开 MCP 页面时出错:",
  "Error opening MCP config modal:": "打开 MCP 配置弹窗时出错:",
  "Error opening configure page:": "打开配置页面时出错:",
  "Error parsing file diff JSON data:": "解析文件差异 JSON 数据时出错:",
  "Failed to close all diff zones:": "关闭所有差异区域失败:",
  "Browser is not enabled for this plan": "此计划未启用浏览器功能",
  "URL is required": "需要 URL",
  "url is required": "需要 url",
  "Missing API key. Please make sure you are signed in to Antigravity. If the problem persists, please restart the IDE.": "缺少 API 密钥。请确保您已登录 Antigravity。如果问题仍然存在，请重启 IDE。",
  "Function not implemented.": "功能未实现。",
  "clientKey is required": "需要 clientKey",
  "appName is required.": "需要 appName。",
  "Objects are not valid as a React child (found:": "对象不是有效的 React 子元素 (发现:",
  "React.Children.only expected to receive a single React element child.": "React.Children.only 期望接收单个 React 元素子节点。",
  "Unknown encoding:": "未知编码:",
  "out of range index": "索引超出范围",
  "BigInt not supported": "不支持 BigInt",
  "invalid base64 string.": "无效的 base64 字符串。",
  "invalid UTF8": "无效的 UTF8",
  "premature EOF": "过早的文件结束",
  "useLanguageServerContext must be used within a LanguageServerContextProvider": "useLanguageServerContext 必须在 LanguageServerContextProvider 中使用",
  "useContextMenuContext must be used within a ContextMenuProvider": "useContextMenuContext 必须在 ContextMenuProvider 中使用",
  "useAgentWorkbenchContext must be used within an AgentWorkbenchContextProvider": "useAgentWorkbenchContext 必须在 AgentWorkbenchContextProvider 中使用",
  "useBrowserContext must be used within a BrowserContextProvider": "useBrowserContext 必须在 BrowserContextProvider 中使用",
  "useRegisterChatClientRequestHandler must be used within a ChatClientServerContextProvider": "useRegisterChatClientRequestHandler 必须在 ChatClientServerContextProvider 中使用",
  "useTrajectorySummariesContext must be used within a TrajectorySummariesProvider": "useTrajectorySummariesContext 必须在 TrajectorySummariesProvider 中使用",
  "useMessageHistoryContext must be used within a MessageHistoryContextProvider": "useMessageHistoryContext 必须在 MessageHistoryContextProvider 中使用",
  "useTokenThemeContext must be used within a TokenThemeContextProvider": "useTokenThemeContext 必须在 TokenThemeContextProvider 中使用",
  "You have to provide an `open` and an `onClose` prop to the `Dialog` component.": "您必须为 `Dialog` 组件提供 `open` 和 `onClose` 属性。",
  "You provided an `onClose` prop to the `Dialog`, but forgot an `open` prop.": "您为 `Dialog` 提供了 `onClose` 属性，但忘记了 `open` 属性。",
  "You provided an `open` prop to the `Dialog`, but forgot an `onClose` prop.": "您为 `Dialog` 提供了 `open` 属性，但忘记了 `onClose` 属性。",
  "Path must be a string. Received": "路径必须是字符串。收到",
  "The URL must be of scheme file": "URL 必须是 file 协议",
  "Generator is already executing.": "生成器已在执行中。",
  "Unknown unit": "未知单位",
  "Unexpected object:": "意外的对象:",
  "unable to serialize": "无法序列化",
  "This undo action will not make any code changes.": "此撤销操作不会进行任何代码更改。",
  "Messages can be sent while the agent is still working and your message will be queued and taken into consideration at the next available break in reasoning.": "您可以在代理仍在工作时发送消息，您的消息将被排队，并在下一个可用的推理间歇时被考虑。",
  "This tool runs code that can access IDE extension APIs and potentially change the functionality of your IDE the same way that an IDE extension or plugin can.": "此工具运行的代码可以访问 IDE 扩展 API，并可能以与 IDE 扩展或插件相同的方式更改 IDE 的功能。",
  "Too many requests, please try again in a bit!": "请求过多，请稍后重试！",
  "This error is likely temporary. You can prompt the model to try again after some time.": "此错误可能是暂时的。您可以稍后提示模型重试。",
  "Get notified when the agent needs your attention or completes a task.": "当代理需要您注意或完成任务时获得通知。",
  "This model is currently experiencing some issues.": "此模型当前遇到一些问题。",
  "Failed to load": "加载失败",
  "Did you make sure to report this error on Slack?": "您确定已在 Slack 上报告此错误了吗？",
  "Standard conversational mode.": "标准对话模式。",
  "Uses Google conversational mixin.": "使用 Google 对话混入。",
  "Uses custom mixin.": "使用自定义混入。",
  "You can prompt the model to try again or start a new conversation if the error persists.": "您可以重试提示模型，或者如果错误持续存在，可以开始新的对话。",
  "for more help.": "获取更多帮助。",
  "On": "开",
  "AI Shortcuts": "AI 快捷键",
  "Manage": "管理",
  "Snooze": "暂停",
  "Manage MCP servers": "管理 MCP 服务器",
  "View raw config": "查看原始配置",
  "Terminal execution policy": "终端执行策略",
  "Review policy": "审查策略",
  "JavaScript execution policy": "JavaScript 执行策略",
  "Disabled": "已禁用",
  "Auto Execution": "自动执行",
  "Clipboard Context": "剪贴板上下文",
  "Enable Tab Sounds (Beta)": "启用 Tab 声音 (Beta)",
  "Set the speed of tab suggestions": "设置 Tab 建议的速度",
  "Open files in the background if the agent creates or edits them": "当 Agent 创建或编辑文件时在后台打开它们",
  "Open Agent panel on window reload": "窗口重新加载时打开 Agent 面板",
  "Predict the location of your next edit and navigates you there with a tab keypress": "预测下一个编辑位置，按 Tab 键即可跳转到该位置",
  "Quickly add and update imports with a tab keypress.": "按 Tab 键快速添加和更新导入语句。",
  "Highlight newly inserted text after accepting a Tab completion.": "接受 Tab 补全后高亮新插入的文本。",
  "Slow": "慢速",
  "Fast": "快速",
  "View and manage Agent memories, workflows, and rules": "查看和管理 Agent 记忆、工作流和规则",
  "Edit your SSH configuration": "编辑你的 SSH 配置",
  "Accept hunk": "接受代码块",
  "Open Agent": "打开 Agent",
  "Reset to default": "重置为默认",
  "Submit": "提交",
  "Open Agent Manager": "打开 Agent 管理器",
  "Settings": "设置",
  "Editor-Specific Settings": "编辑器特定设置",
  "Accept Changes": "接受更改",
  "Hide selection nudge": "隐藏选中操作提示",
  "Open Diff": "打开差异",
  "Additional Options": "其他选项",
  "Try Again": "再试一次",
  "Add Context": "添加上下文",
  "Open Conversation Picker": "打开对话选择器",
  "Open File Search": "打开文件搜索",
  "Focus Input": "聚焦输入框",
  "New Conversation": "新建对话",
  "Open Workspace Selector": "打开工作区选择器",
  "Go Back": "后退",
  "Go Forward": "前进",
  "File Picker": "文件选择器",
  "Toggle Editor": "切换编辑器",
  "Select Previous Conversation": "选择上一个对话",
  "Select Next Conversation": "选择下一个对话",
  "Toggle Model Selector": "切换模型选择器",
  "Start Voice Recording": "开始语音录制",
  "Stop Voice Recording": "停止语音录制",
  "Find in Pane": "在窗格中查找",
  "Toggle Sidebar": "切换侧边栏",
  "Toggle Auxiliary Pane": "切换辅助窗格",
  "Toggle Terminal": "切换终端",
  "Open Settings": "打开设置",
  "Zoom In": "放大",
  "Zoom Out": "缩小",
  "Reset Zoom": "重置缩放",
  "Navigation": "导航",
  "Layout Controls": "布局控制",
  "Shortcuts": "快捷键",
  "Keyboard shortcuts for quick navigation and control.": "用于快速导航和控制的键盘快捷键。",
  "Feedback Type": "反馈类型",
  "Please describe the issue in detail. The more actionable your feedback, the quicker our team can address your request. Some helpful information includes:": "请详细描述该问题。您的反馈越具可操作性，我们的团队就能越快处理您的请求。一些有帮助的信息包括：",
  "Steps to reproduce the issue": "重现问题的步骤",
  "Expected behavior": "预期行为",
  "Actual behavior": "实际行为",
  "Any error messages": "任何错误消息",
  "Any relevant information": "任何相关信息",
  "Steps to Reproduce": "重现步骤",
  "Please list the steps to reproduce the issue": "请列出重现该问题的步骤",
  "Attach a screenshot (optional)": "附加屏幕截图 (可选)",
  "Attach Antigravity server logs": "附加 Antigravity 服务器日志",
  "Send feedback as": "发送反馈，身份为：",
  "We recommend attaching logs. Attaching logs will help the Antigravity team act on and prioritize your feedback.": "我们建议附加日志。附加日志将帮助 Antigravity 团队针对您的反馈进行处理并排定优先级。",
  "Model quota reached": "已达到模型配额限制",
  "Upgrade": "升级",
  "Thinking for ": "思考中 ",
  "Thought for ": "思考了 ",
  "Changes Overview": "更改概览",
  "Settings - ": "设置 - "
};

    function translateTextNode(node) {
        if (node.nodeType === Node.TEXT_NODE) {
            const originalText = node.nodeValue;
            let text = originalText.trim();
            if (!text) return;
            
            if (dict[text]) {
                node.nodeValue = originalText.replace(text, dict[text]);
                return;
            }

            // 动态前缀匹配
            if (text.startsWith("Thinking for ")) {
                node.nodeValue = originalText.replace(text, "思考中 " + text.substring("Thinking for ".length));
                return;
            }
            if (text.startsWith("Thought for ")) {
                node.nodeValue = originalText.replace(text, "思考了 " + text.substring("Thought for ".length));
                return;
            }
            if (text.startsWith("Changes Overview (")) {
                node.nodeValue = originalText.replace(text, text.replace("Changes Overview", "更改概览"));
                return;
            }
            if (text.startsWith("Terminal (") && text.includes(")")) {
                node.nodeValue = originalText.replace(text, text.replace("Terminal", "终端"));
                return;
            }
        }
    }

    function translateAttributes(node) {
        if (node.nodeType === Node.ELEMENT_NODE) {
            ['aria-label', 'title', 'placeholder'].forEach(attr => {
                if (node.hasAttribute(attr)) {
                    const val = node.getAttribute(attr);
                    if (val && dict[val]) {
                        node.setAttribute(attr, dict[val]);
                    }
                }
            });
        }
    }

    // 使用 C++ 级的 TreeWalker 进行极速文本遍历，解决界面卡顿问题
    function processTree(root) {
        if (root.nodeType === Node.TEXT_NODE) {
            translateTextNode(root);
            return;
        }
        
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null, false);
        let node;
        while (node = walker.nextNode()) {
            translateTextNode(node);
        }
        
        if (root.nodeType === Node.ELEMENT_NODE) {
            translateAttributes(root);
            const elements = root.querySelectorAll('*');
            for (let i = 0; i < elements.length; i++) {
                translateAttributes(elements[i]);
            }
        }
    }

    let isTranslating = false;
    const observer = new MutationObserver((mutations) => {
        if (isTranslating) return;
        isTranslating = true;
        
        // 批量处理 mutations 以提升性能
        const targetNodes = new Set();
        mutations.forEach((mutation) => {
            if (mutation.type === 'childList') {
                mutation.addedNodes.forEach(node => {
                    if (node.tagName !== 'SCRIPT' && node.tagName !== 'STYLE') {
                        targetNodes.add(node);
                    }
                });
            } else if (mutation.type === 'characterData') {
                translateTextNode(mutation.target);
            } else if (mutation.type === 'attributes') {
                const node = mutation.target;
                const attr = mutation.attributeName;
                const val = node.getAttribute(attr);
                if (val && dict[val]) {
                    node.setAttribute(attr, dict[val]);
                }
            }
        });
        
        targetNodes.forEach(node => processTree(node));
        
        isTranslating = false;
    });

    function init() {
        if (document.body) {
            processTree(document.body);
            observer.observe(document.body, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ['aria-label', 'title', 'placeholder'] });
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
